### ISSUE TITLE
feat: support TryFrom<SurrealValue>> for Relate

### ISSUE THREAD

**Issue by huang12zheng** [KeatonTech/surrealdb-schema-derive#2]
`relate mobile:123->identity->account:hz`
would get 
```
[src/account_manage.rs:6] &v = [
    Object(
        Object(
            {
                "id": Thing(
                    Thing {
                        tb: "identity",
                        id: String(
                            "lc8glgip0jrvvfmc6nhs",
                        ),
                    },
                ),
                "in": Thing(
                    Thing {
                        tb: "mobile",
                        id: Number(
                            123,
                        ),
                    },
                ),
                "out": Thing(
                    Thing {
                        tb: "account",
                        id: String(
                            "hz",
                        ),
                    },
                ),
            },
        ),
    ),
]
```
For convenience, I think I need to implement a new Model as Relation, which is impl `TryFrom<SurrealValue>> for Relate`
```rs
struct Relation {
    pub id: String,
    pub from: String,
    pub table: String,
    pub with: String,
}
```
What do you think?

**Comment by KeatonTech** [comment]
Yeah I've been thinking of adding another derive called something like `SurrealDbRelation`. Relations are certainly one of the most interesting and useful features of Surreal! The syntax for defining them is not well documented though, and I'd prefer to keep this library using only `SCHEMAFULL` features of SurrealDb since type safety is kind of a cornerstone of Rust. So that's slowing me down a bit

**Comment by huang12zheng** [comment]
I look forward to your work: )

**Comment by huang12zheng** [comment]
I realize I may have missed one
`in prop` can not appear in the schema.
I hope you know that, too
@KeatonTech 
```
struct Relation {
    pub id: String,
    pub in: String,   // get error
    pub table: String,
    pub with: String,
}
```
